// The MIT License
//
// Copyright (c) 2022 Temporal Technologies Inc.  All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/api/taskqueue/v1/message.proto

package taskqueue

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	types "github.com/gogo/protobuf/types"
	v11 "go.temporal.io/api/common/v1"
	v1 "go.temporal.io/api/enums/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// See https://docs.temporal.io/docs/concepts/task-queues/
type TaskQueue struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Default: TASK_QUEUE_KIND_NORMAL.
	Kind v1.TaskQueueKind `protobuf:"varint,2,opt,name=kind,proto3,enum=temporal.api.enums.v1.TaskQueueKind" json:"kind,omitempty"`
}

func (m *TaskQueue) Reset()      { *m = TaskQueue{} }
func (*TaskQueue) ProtoMessage() {}
func (*TaskQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{0}
}
func (m *TaskQueue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskQueue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskQueue.Merge(m, src)
}
func (m *TaskQueue) XXX_Size() int {
	return m.Size()
}
func (m *TaskQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskQueue.DiscardUnknown(m)
}

var xxx_messageInfo_TaskQueue proto.InternalMessageInfo

func (m *TaskQueue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskQueue) GetKind() v1.TaskQueueKind {
	if m != nil {
		return m.Kind
	}
	return v1.TASK_QUEUE_KIND_UNSPECIFIED
}

// Only applies to activity task queues
type TaskQueueMetadata struct {
	// Allows throttling dispatch of tasks from this queue
	MaxTasksPerSecond *types.DoubleValue `protobuf:"bytes,1,opt,name=max_tasks_per_second,json=maxTasksPerSecond,proto3" json:"max_tasks_per_second,omitempty"`
}

func (m *TaskQueueMetadata) Reset()      { *m = TaskQueueMetadata{} }
func (*TaskQueueMetadata) ProtoMessage() {}
func (*TaskQueueMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{1}
}
func (m *TaskQueueMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskQueueMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskQueueMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskQueueMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskQueueMetadata.Merge(m, src)
}
func (m *TaskQueueMetadata) XXX_Size() int {
	return m.Size()
}
func (m *TaskQueueMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskQueueMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TaskQueueMetadata proto.InternalMessageInfo

func (m *TaskQueueMetadata) GetMaxTasksPerSecond() *types.DoubleValue {
	if m != nil {
		return m.MaxTasksPerSecond
	}
	return nil
}

type TaskQueueStatus struct {
	BacklogCountHint int64        `protobuf:"varint,1,opt,name=backlog_count_hint,json=backlogCountHint,proto3" json:"backlog_count_hint,omitempty"`
	ReadLevel        int64        `protobuf:"varint,2,opt,name=read_level,json=readLevel,proto3" json:"read_level,omitempty"`
	AckLevel         int64        `protobuf:"varint,3,opt,name=ack_level,json=ackLevel,proto3" json:"ack_level,omitempty"`
	RatePerSecond    float64      `protobuf:"fixed64,4,opt,name=rate_per_second,json=ratePerSecond,proto3" json:"rate_per_second,omitempty"`
	TaskIdBlock      *TaskIdBlock `protobuf:"bytes,5,opt,name=task_id_block,json=taskIdBlock,proto3" json:"task_id_block,omitempty"`
}

func (m *TaskQueueStatus) Reset()      { *m = TaskQueueStatus{} }
func (*TaskQueueStatus) ProtoMessage() {}
func (*TaskQueueStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{2}
}
func (m *TaskQueueStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskQueueStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskQueueStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskQueueStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskQueueStatus.Merge(m, src)
}
func (m *TaskQueueStatus) XXX_Size() int {
	return m.Size()
}
func (m *TaskQueueStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskQueueStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TaskQueueStatus proto.InternalMessageInfo

func (m *TaskQueueStatus) GetBacklogCountHint() int64 {
	if m != nil {
		return m.BacklogCountHint
	}
	return 0
}

func (m *TaskQueueStatus) GetReadLevel() int64 {
	if m != nil {
		return m.ReadLevel
	}
	return 0
}

func (m *TaskQueueStatus) GetAckLevel() int64 {
	if m != nil {
		return m.AckLevel
	}
	return 0
}

func (m *TaskQueueStatus) GetRatePerSecond() float64 {
	if m != nil {
		return m.RatePerSecond
	}
	return 0
}

func (m *TaskQueueStatus) GetTaskIdBlock() *TaskIdBlock {
	if m != nil {
		return m.TaskIdBlock
	}
	return nil
}

type TaskIdBlock struct {
	StartId int64 `protobuf:"varint,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	EndId   int64 `protobuf:"varint,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
}

func (m *TaskIdBlock) Reset()      { *m = TaskIdBlock{} }
func (*TaskIdBlock) ProtoMessage() {}
func (*TaskIdBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{3}
}
func (m *TaskIdBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskIdBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskIdBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskIdBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskIdBlock.Merge(m, src)
}
func (m *TaskIdBlock) XXX_Size() int {
	return m.Size()
}
func (m *TaskIdBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskIdBlock.DiscardUnknown(m)
}

var xxx_messageInfo_TaskIdBlock proto.InternalMessageInfo

func (m *TaskIdBlock) GetStartId() int64 {
	if m != nil {
		return m.StartId
	}
	return 0
}

func (m *TaskIdBlock) GetEndId() int64 {
	if m != nil {
		return m.EndId
	}
	return 0
}

type TaskQueuePartitionMetadata struct {
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	OwnerHostName string `protobuf:"bytes,2,opt,name=owner_host_name,json=ownerHostName,proto3" json:"owner_host_name,omitempty"`
}

func (m *TaskQueuePartitionMetadata) Reset()      { *m = TaskQueuePartitionMetadata{} }
func (*TaskQueuePartitionMetadata) ProtoMessage() {}
func (*TaskQueuePartitionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{4}
}
func (m *TaskQueuePartitionMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskQueuePartitionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskQueuePartitionMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskQueuePartitionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskQueuePartitionMetadata.Merge(m, src)
}
func (m *TaskQueuePartitionMetadata) XXX_Size() int {
	return m.Size()
}
func (m *TaskQueuePartitionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskQueuePartitionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TaskQueuePartitionMetadata proto.InternalMessageInfo

func (m *TaskQueuePartitionMetadata) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TaskQueuePartitionMetadata) GetOwnerHostName() string {
	if m != nil {
		return m.OwnerHostName
	}
	return ""
}

type PollerInfo struct {
	LastAccessTime *time.Time `protobuf:"bytes,1,opt,name=last_access_time,json=lastAccessTime,proto3,stdtime" json:"last_access_time,omitempty"`
	Identity       string     `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	RatePerSecond  float64    `protobuf:"fixed64,3,opt,name=rate_per_second,json=ratePerSecond,proto3" json:"rate_per_second,omitempty"`
	// If a worker has opted into the worker versioning feature while polling, its capabilities will
	// appear here.
	WorkerVersionCapabilities *v11.WorkerVersionCapabilities `protobuf:"bytes,4,opt,name=worker_version_capabilities,json=workerVersionCapabilities,proto3" json:"worker_version_capabilities,omitempty"`
}

func (m *PollerInfo) Reset()      { *m = PollerInfo{} }
func (*PollerInfo) ProtoMessage() {}
func (*PollerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{5}
}
func (m *PollerInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PollerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PollerInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PollerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollerInfo.Merge(m, src)
}
func (m *PollerInfo) XXX_Size() int {
	return m.Size()
}
func (m *PollerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PollerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PollerInfo proto.InternalMessageInfo

func (m *PollerInfo) GetLastAccessTime() *time.Time {
	if m != nil {
		return m.LastAccessTime
	}
	return nil
}

func (m *PollerInfo) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *PollerInfo) GetRatePerSecond() float64 {
	if m != nil {
		return m.RatePerSecond
	}
	return 0
}

func (m *PollerInfo) GetWorkerVersionCapabilities() *v11.WorkerVersionCapabilities {
	if m != nil {
		return m.WorkerVersionCapabilities
	}
	return nil
}

type StickyExecutionAttributes struct {
	WorkerTaskQueue *TaskQueue `protobuf:"bytes,1,opt,name=worker_task_queue,json=workerTaskQueue,proto3" json:"worker_task_queue,omitempty"`
	// (-- api-linter: core::0140::prepositions=disabled
	//
	//	aip.dev/not-precedent: "to" is used to indicate interval. --)
	ScheduleToStartTimeout *time.Duration `protobuf:"bytes,2,opt,name=schedule_to_start_timeout,json=scheduleToStartTimeout,proto3,stdduration" json:"schedule_to_start_timeout,omitempty"`
}

func (m *StickyExecutionAttributes) Reset()      { *m = StickyExecutionAttributes{} }
func (*StickyExecutionAttributes) ProtoMessage() {}
func (*StickyExecutionAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{6}
}
func (m *StickyExecutionAttributes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StickyExecutionAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StickyExecutionAttributes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StickyExecutionAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StickyExecutionAttributes.Merge(m, src)
}
func (m *StickyExecutionAttributes) XXX_Size() int {
	return m.Size()
}
func (m *StickyExecutionAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_StickyExecutionAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_StickyExecutionAttributes proto.InternalMessageInfo

func (m *StickyExecutionAttributes) GetWorkerTaskQueue() *TaskQueue {
	if m != nil {
		return m.WorkerTaskQueue
	}
	return nil
}

func (m *StickyExecutionAttributes) GetScheduleToStartTimeout() *time.Duration {
	if m != nil {
		return m.ScheduleToStartTimeout
	}
	return nil
}

// Used by the worker versioning APIs, represents an unordered set of one or more versions which are
// considered to be compatible with each other. Currently the versions are always worker build IDs.
type CompatibleVersionSet struct {
	// All the compatible versions, unordered, except for the last element, which is considered the set "default".
	BuildIds []string `protobuf:"bytes,1,rep,name=build_ids,json=buildIds,proto3" json:"build_ids,omitempty"`
}

func (m *CompatibleVersionSet) Reset()      { *m = CompatibleVersionSet{} }
func (*CompatibleVersionSet) ProtoMessage() {}
func (*CompatibleVersionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{7}
}
func (m *CompatibleVersionSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompatibleVersionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompatibleVersionSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CompatibleVersionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompatibleVersionSet.Merge(m, src)
}
func (m *CompatibleVersionSet) XXX_Size() int {
	return m.Size()
}
func (m *CompatibleVersionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CompatibleVersionSet.DiscardUnknown(m)
}

var xxx_messageInfo_CompatibleVersionSet proto.InternalMessageInfo

func (m *CompatibleVersionSet) GetBuildIds() []string {
	if m != nil {
		return m.BuildIds
	}
	return nil
}

// Reachability of tasks for a worker on a single task queue.
type TaskQueueReachability struct {
	TaskQueue string `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	// Task reachability for a worker in a single task queue.
	// See the TaskReachability docstring for information about each enum variant.
	// If reachability is empty, this worker is considered unreachable in this task queue.
	Reachability []v1.TaskReachability `protobuf:"varint,2,rep,packed,name=reachability,proto3,enum=temporal.api.enums.v1.TaskReachability" json:"reachability,omitempty"`
}

func (m *TaskQueueReachability) Reset()      { *m = TaskQueueReachability{} }
func (*TaskQueueReachability) ProtoMessage() {}
func (*TaskQueueReachability) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{8}
}
func (m *TaskQueueReachability) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskQueueReachability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskQueueReachability.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskQueueReachability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskQueueReachability.Merge(m, src)
}
func (m *TaskQueueReachability) XXX_Size() int {
	return m.Size()
}
func (m *TaskQueueReachability) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskQueueReachability.DiscardUnknown(m)
}

var xxx_messageInfo_TaskQueueReachability proto.InternalMessageInfo

func (m *TaskQueueReachability) GetTaskQueue() string {
	if m != nil {
		return m.TaskQueue
	}
	return ""
}

func (m *TaskQueueReachability) GetReachability() []v1.TaskReachability {
	if m != nil {
		return m.Reachability
	}
	return nil
}

// Reachability of tasks for a worker by build id, in one or more task queues.
type BuildIdReachability struct {
	// A build id or empty if unversioned.
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// Reachability per task queue.
	TaskQueueReachability []*TaskQueueReachability `protobuf:"bytes,2,rep,name=task_queue_reachability,json=taskQueueReachability,proto3" json:"task_queue_reachability,omitempty"`
}

func (m *BuildIdReachability) Reset()      { *m = BuildIdReachability{} }
func (*BuildIdReachability) ProtoMessage() {}
func (*BuildIdReachability) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60437e4ccf51d94, []int{9}
}
func (m *BuildIdReachability) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BuildIdReachability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BuildIdReachability.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BuildIdReachability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildIdReachability.Merge(m, src)
}
func (m *BuildIdReachability) XXX_Size() int {
	return m.Size()
}
func (m *BuildIdReachability) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildIdReachability.DiscardUnknown(m)
}

var xxx_messageInfo_BuildIdReachability proto.InternalMessageInfo

func (m *BuildIdReachability) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *BuildIdReachability) GetTaskQueueReachability() []*TaskQueueReachability {
	if m != nil {
		return m.TaskQueueReachability
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskQueue)(nil), "temporal.api.taskqueue.v1.TaskQueue")
	proto.RegisterType((*TaskQueueMetadata)(nil), "temporal.api.taskqueue.v1.TaskQueueMetadata")
	proto.RegisterType((*TaskQueueStatus)(nil), "temporal.api.taskqueue.v1.TaskQueueStatus")
	proto.RegisterType((*TaskIdBlock)(nil), "temporal.api.taskqueue.v1.TaskIdBlock")
	proto.RegisterType((*TaskQueuePartitionMetadata)(nil), "temporal.api.taskqueue.v1.TaskQueuePartitionMetadata")
	proto.RegisterType((*PollerInfo)(nil), "temporal.api.taskqueue.v1.PollerInfo")
	proto.RegisterType((*StickyExecutionAttributes)(nil), "temporal.api.taskqueue.v1.StickyExecutionAttributes")
	proto.RegisterType((*CompatibleVersionSet)(nil), "temporal.api.taskqueue.v1.CompatibleVersionSet")
	proto.RegisterType((*TaskQueueReachability)(nil), "temporal.api.taskqueue.v1.TaskQueueReachability")
	proto.RegisterType((*BuildIdReachability)(nil), "temporal.api.taskqueue.v1.BuildIdReachability")
}

func init() {
	proto.RegisterFile("temporal/api/taskqueue/v1/message.proto", fileDescriptor_c60437e4ccf51d94)
}

var fileDescriptor_c60437e4ccf51d94 = []byte{
	// 966 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xd8, 0x69, 0x1b, 0x8f, 0x9b, 0x7f, 0x4b, 0x03, 0x71, 0x52, 0xb6, 0x61, 0x15, 0xa5,
	0x41, 0x42, 0x6b, 0xec, 0x5e, 0x90, 0x39, 0xa0, 0x38, 0x20, 0x35, 0x2d, 0x41, 0x66, 0x6d, 0x19,
	0xd1, 0xcb, 0x6a, 0xbc, 0xfb, 0x6a, 0x8f, 0xf6, 0xcf, 0x6c, 0x77, 0x66, 0x9d, 0xe4, 0x86, 0xc4,
	0x07, 0xa0, 0x47, 0xc4, 0x27, 0x40, 0x7c, 0x12, 0x90, 0x38, 0xe4, 0xd8, 0x1b, 0xc4, 0xb9, 0x20,
	0x2e, 0xf4, 0x23, 0xa0, 0x99, 0x5d, 0xaf, 0xed, 0x3a, 0x81, 0xde, 0x3c, 0xef, 0xf7, 0xde, 0xcc,
	0xef, 0xf7, 0x7e, 0xef, 0xad, 0xf1, 0x43, 0x01, 0x41, 0xc4, 0x62, 0xe2, 0xd7, 0x48, 0x44, 0x6b,
	0x82, 0x70, 0xef, 0x45, 0x02, 0x09, 0xd4, 0x46, 0xf5, 0x5a, 0x00, 0x9c, 0x93, 0x01, 0x98, 0x51,
	0xcc, 0x04, 0xd3, 0xaa, 0x93, 0x44, 0x93, 0x44, 0xd4, 0xcc, 0x13, 0xcd, 0x51, 0x7d, 0x5b, 0x1f,
	0x30, 0x36, 0xf0, 0xa1, 0xa6, 0x12, 0xfb, 0xc9, 0xf3, 0x9a, 0x9b, 0xc4, 0x44, 0x50, 0x16, 0xa6,
	0xa5, 0xdb, 0x0f, 0xde, 0xc4, 0x05, 0x0d, 0x80, 0x0b, 0x12, 0x44, 0x59, 0xc2, 0xc2, 0x05, 0xa7,
	0x31, 0x89, 0x22, 0x88, 0x79, 0x86, 0x7f, 0xe0, 0x42, 0x04, 0xa1, 0x0b, 0xa1, 0x43, 0x81, 0xd7,
	0x06, 0x6c, 0xc0, 0x54, 0x5c, 0xfd, 0xca, 0x52, 0xf6, 0xe7, 0x74, 0x40, 0x98, 0x04, 0x5c, 0x6a,
	0x90, 0x3c, 0xed, 0x94, 0x68, 0x9a, 0xb7, 0x37, 0x97, 0xe7, 0xb0, 0x20, 0x60, 0xe1, 0x82, 0x58,
	0xe3, 0x5b, 0x5c, 0xee, 0x12, 0xee, 0x7d, 0x2d, 0x0b, 0x35, 0x0d, 0x2f, 0x85, 0x24, 0x80, 0x2d,
	0xb4, 0x8b, 0x0e, 0xca, 0x96, 0xfa, 0xad, 0x7d, 0x82, 0x97, 0x3c, 0x1a, 0xba, 0x5b, 0xc5, 0x5d,
	0x74, 0xb0, 0xda, 0xd8, 0x33, 0xe7, 0x9a, 0xa3, 0x5e, 0x37, 0x47, 0x75, 0x33, 0xbf, 0xe3, 0x29,
	0x0d, 0x5d, 0x4b, 0x55, 0x18, 0x7d, 0xbc, 0x91, 0x87, 0x4f, 0x40, 0x10, 0x97, 0x08, 0xa2, 0x9d,
	0xe0, 0x7b, 0x01, 0x39, 0xb3, 0x25, 0x5b, 0x6e, 0x47, 0x10, 0xdb, 0x1c, 0x1c, 0x16, 0xba, 0xea,
	0xc9, 0x4a, 0xe3, 0xbe, 0x99, 0xf6, 0xc7, 0x9c, 0xf4, 0xc7, 0xfc, 0x9c, 0x25, 0x7d, 0x1f, 0x7a,
	0xc4, 0x4f, 0xc0, 0xda, 0x08, 0xc8, 0x99, 0xbc, 0x91, 0xb7, 0x21, 0xee, 0xa8, 0x32, 0xe3, 0x1f,
	0x84, 0xd7, 0xf2, 0x47, 0x3a, 0x82, 0x88, 0x84, 0x6b, 0x1f, 0x61, 0xad, 0x4f, 0x1c, 0xcf, 0x67,
	0x03, 0xdb, 0x61, 0x49, 0x28, 0xec, 0x21, 0x0d, 0x85, 0x7a, 0xa0, 0x64, 0xad, 0x67, 0xc8, 0x91,
	0x04, 0x1e, 0xd3, 0x50, 0x68, 0xef, 0x63, 0x1c, 0x03, 0x71, 0x6d, 0x1f, 0x46, 0xe0, 0x2b, 0x95,
	0x25, 0xab, 0x2c, 0x23, 0x5f, 0xca, 0x80, 0xb6, 0x83, 0xcb, 0xc4, 0xf1, 0x32, 0xb4, 0xa4, 0xd0,
	0x65, 0xe2, 0x78, 0x29, 0xb8, 0x8f, 0xd7, 0x62, 0x22, 0x60, 0x56, 0xc7, 0xd2, 0x2e, 0x3a, 0x40,
	0xd6, 0x8a, 0x0c, 0xe7, 0x2c, 0xb5, 0x27, 0x78, 0x45, 0xd9, 0x43, 0x5d, 0xbb, 0xef, 0x33, 0xc7,
	0xdb, 0xba, 0xa5, 0xd4, 0xee, 0x9b, 0x37, 0x4e, 0x9a, 0x6a, 0xe8, 0xb1, 0xdb, 0x92, 0xd9, 0x56,
	0x45, 0x4c, 0x0f, 0xc6, 0x67, 0xb8, 0x32, 0x83, 0x69, 0x55, 0xbc, 0xcc, 0x05, 0x89, 0x85, 0x4d,
	0xdd, 0x4c, 0xe2, 0x1d, 0x75, 0x3e, 0x76, 0xb5, 0x4d, 0x7c, 0x1b, 0x42, 0x57, 0x02, 0xa9, 0xaa,
	0x5b, 0x10, 0xba, 0xc7, 0xae, 0xd1, 0xc3, 0xdb, 0x79, 0xc7, 0xda, 0x24, 0x16, 0x54, 0xce, 0x6f,
	0xee, 0xcf, 0x3a, 0x2e, 0x79, 0x70, 0x9e, 0x4d, 0x80, 0xfc, 0x29, 0x45, 0xb2, 0xd3, 0x10, 0x62,
	0x7b, 0xc8, 0xb8, 0xb0, 0xd5, 0x7c, 0x14, 0x15, 0xba, 0xa2, 0xc2, 0x8f, 0x19, 0x17, 0x5f, 0x91,
	0x00, 0x8c, 0x1f, 0x8a, 0x18, 0xb7, 0x99, 0xef, 0x43, 0x7c, 0x1c, 0x3e, 0x67, 0xda, 0x13, 0xbc,
	0xee, 0x13, 0x2e, 0x6c, 0xe2, 0x38, 0xc0, 0xb9, 0x2d, 0x17, 0x21, 0x33, 0x79, 0x7b, 0xc1, 0xe4,
	0xee, 0x64, 0x4b, 0x5a, 0x4b, 0x2f, 0xff, 0x78, 0x80, 0xac, 0x55, 0x59, 0x79, 0xa8, 0x0a, 0x25,
	0xa4, 0x6d, 0xe3, 0x65, 0xea, 0x42, 0x28, 0xa8, 0x38, 0xcf, 0xde, 0xce, 0xcf, 0xd7, 0x79, 0x50,
	0xba, 0xce, 0x83, 0x17, 0x78, 0xe7, 0x94, 0xc5, 0x1e, 0xc4, 0xf6, 0x08, 0x62, 0x4e, 0x59, 0x68,
	0x3b, 0x24, 0x22, 0x7d, 0xea, 0x53, 0x41, 0x81, 0x2b, 0xdf, 0x2a, 0x8d, 0xfa, 0xbc, 0x23, 0xe9,
	0xd2, 0x48, 0x3b, 0xbe, 0x51, 0xa5, 0xbd, 0xb4, 0xf2, 0x68, 0xa6, 0xd0, 0xaa, 0x9e, 0xde, 0x04,
	0x19, 0xbf, 0x21, 0x5c, 0xed, 0x08, 0xea, 0x78, 0xe7, 0x5f, 0x9c, 0x81, 0x93, 0xc8, 0x3e, 0x1f,
	0x0a, 0x11, 0xd3, 0x7e, 0x22, 0x80, 0x6b, 0x6d, 0xbc, 0x91, 0x11, 0x9a, 0xae, 0x6e, 0xd6, 0xa1,
	0xbd, 0xff, 0x19, 0x0c, 0xe5, 0x9d, 0xb5, 0x96, 0x96, 0x4f, 0xd7, 0xf7, 0x19, 0xae, 0x72, 0x67,
	0x08, 0x6e, 0xe2, 0x83, 0x2d, 0x98, 0x9d, 0xce, 0x85, 0x6c, 0x3c, 0x4b, 0x84, 0xea, 0x5b, 0xa5,
	0x51, 0x5d, 0x5c, 0xb0, 0xec, 0x0b, 0xd6, 0x5a, 0xfa, 0x51, 0xb6, 0xfe, 0xdd, 0xc9, 0x0d, 0x5d,
	0xd6, 0x91, 0xf5, 0xdd, 0xb4, 0xdc, 0x78, 0x84, 0xef, 0x1d, 0xb1, 0x20, 0x22, 0x82, 0xca, 0x75,
	0x4c, 0xc5, 0x76, 0x40, 0xc8, 0xfd, 0xe8, 0x27, 0xd4, 0x97, 0x63, 0xc6, 0xb7, 0xd0, 0x6e, 0x49,
	0x7a, 0xa3, 0x02, 0xc7, 0x2e, 0x37, 0xbe, 0x47, 0x78, 0x73, 0xca, 0x17, 0x88, 0x33, 0x4c, 0x9b,
	0x73, 0x2e, 0xb7, 0xee, 0x0d, 0xd5, 0x65, 0xab, 0x2c, 0x72, 0x25, 0x4f, 0xf1, 0xdd, 0x78, 0x26,
	0x7d, 0xab, 0xb8, 0x5b, 0x3a, 0x58, 0x6d, 0x3c, 0xfc, 0x8f, 0x8f, 0xcf, 0xec, 0xed, 0xd6, 0x5c,
	0xb1, 0xf1, 0x13, 0xc2, 0xef, 0xb4, 0x52, 0x4a, 0x73, 0x1c, 0xaa, 0x78, 0x79, 0x42, 0x3d, 0x63,
	0x70, 0x27, 0x63, 0xae, 0x0d, 0xf1, 0x7b, 0x53, 0x7a, 0xf6, 0x02, 0x95, 0x4a, 0xe3, 0xe3, 0xb7,
	0x72, 0x68, 0x96, 0xd3, 0xa6, 0xb8, 0x2e, 0xdc, 0xfa, 0x1d, 0x5d, 0x5c, 0xea, 0x85, 0x57, 0x97,
	0x7a, 0xe1, 0xf5, 0xa5, 0x8e, 0xbe, 0x1b, 0xeb, 0xe8, 0xe7, 0xb1, 0x8e, 0x7e, 0x1d, 0xeb, 0xe8,
	0x62, 0xac, 0xa3, 0x3f, 0xc7, 0x3a, 0xfa, 0x6b, 0xac, 0x17, 0x5e, 0x8f, 0x75, 0xf4, 0xf2, 0x4a,
	0x2f, 0x5c, 0x5c, 0xe9, 0x85, 0x57, 0x57, 0x7a, 0x01, 0xdf, 0xa7, 0xec, 0x66, 0x06, 0xad, 0xbb,
	0x27, 0xe9, 0x37, 0xbe, 0x2d, 0x4d, 0x6e, 0xa3, 0x67, 0x1f, 0x0e, 0x66, 0xb2, 0x29, 0x5b, 0xf8,
	0x03, 0xfc, 0x34, 0x3f, 0xfc, 0x52, 0xdc, 0xe9, 0x66, 0x89, 0x94, 0x99, 0x87, 0x11, 0x9d, 0xaa,
	0x31, 0x7b, 0xf5, 0xbf, 0x8b, 0xfa, 0x14, 0x6d, 0x36, 0x0f, 0x23, 0xda, 0x6c, 0xe6, 0x78, 0xb3,
	0xd9, 0xab, 0xf7, 0x6f, 0xab, 0xb9, 0x7a, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xf1,
	0xe7, 0xeb, 0x6d, 0x07, 0x00, 0x00,
}

func (this *TaskQueue) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskQueue)
	if !ok {
		that2, ok := that.(TaskQueue)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Kind != that1.Kind {
		return false
	}
	return true
}
func (this *TaskQueueMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskQueueMetadata)
	if !ok {
		that2, ok := that.(TaskQueueMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MaxTasksPerSecond.Equal(that1.MaxTasksPerSecond) {
		return false
	}
	return true
}
func (this *TaskQueueStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskQueueStatus)
	if !ok {
		that2, ok := that.(TaskQueueStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BacklogCountHint != that1.BacklogCountHint {
		return false
	}
	if this.ReadLevel != that1.ReadLevel {
		return false
	}
	if this.AckLevel != that1.AckLevel {
		return false
	}
	if this.RatePerSecond != that1.RatePerSecond {
		return false
	}
	if !this.TaskIdBlock.Equal(that1.TaskIdBlock) {
		return false
	}
	return true
}
func (this *TaskIdBlock) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskIdBlock)
	if !ok {
		that2, ok := that.(TaskIdBlock)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StartId != that1.StartId {
		return false
	}
	if this.EndId != that1.EndId {
		return false
	}
	return true
}
func (this *TaskQueuePartitionMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskQueuePartitionMetadata)
	if !ok {
		that2, ok := that.(TaskQueuePartitionMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Key != that1.Key {
		return false
	}
	if this.OwnerHostName != that1.OwnerHostName {
		return false
	}
	return true
}
func (this *PollerInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PollerInfo)
	if !ok {
		that2, ok := that.(PollerInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.LastAccessTime == nil {
		if this.LastAccessTime != nil {
			return false
		}
	} else if !this.LastAccessTime.Equal(*that1.LastAccessTime) {
		return false
	}
	if this.Identity != that1.Identity {
		return false
	}
	if this.RatePerSecond != that1.RatePerSecond {
		return false
	}
	if !this.WorkerVersionCapabilities.Equal(that1.WorkerVersionCapabilities) {
		return false
	}
	return true
}
func (this *StickyExecutionAttributes) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StickyExecutionAttributes)
	if !ok {
		that2, ok := that.(StickyExecutionAttributes)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.WorkerTaskQueue.Equal(that1.WorkerTaskQueue) {
		return false
	}
	if this.ScheduleToStartTimeout != nil && that1.ScheduleToStartTimeout != nil {
		if *this.ScheduleToStartTimeout != *that1.ScheduleToStartTimeout {
			return false
		}
	} else if this.ScheduleToStartTimeout != nil {
		return false
	} else if that1.ScheduleToStartTimeout != nil {
		return false
	}
	return true
}
func (this *CompatibleVersionSet) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CompatibleVersionSet)
	if !ok {
		that2, ok := that.(CompatibleVersionSet)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.BuildIds) != len(that1.BuildIds) {
		return false
	}
	for i := range this.BuildIds {
		if this.BuildIds[i] != that1.BuildIds[i] {
			return false
		}
	}
	return true
}
func (this *TaskQueueReachability) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskQueueReachability)
	if !ok {
		that2, ok := that.(TaskQueueReachability)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TaskQueue != that1.TaskQueue {
		return false
	}
	if len(this.Reachability) != len(that1.Reachability) {
		return false
	}
	for i := range this.Reachability {
		if this.Reachability[i] != that1.Reachability[i] {
			return false
		}
	}
	return true
}
func (this *BuildIdReachability) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BuildIdReachability)
	if !ok {
		that2, ok := that.(BuildIdReachability)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BuildId != that1.BuildId {
		return false
	}
	if len(this.TaskQueueReachability) != len(that1.TaskQueueReachability) {
		return false
	}
	for i := range this.TaskQueueReachability {
		if !this.TaskQueueReachability[i].Equal(that1.TaskQueueReachability[i]) {
			return false
		}
	}
	return true
}
func (this *TaskQueue) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&taskqueue.TaskQueue{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Kind: "+fmt.Sprintf("%#v", this.Kind)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TaskQueueMetadata) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&taskqueue.TaskQueueMetadata{")
	if this.MaxTasksPerSecond != nil {
		s = append(s, "MaxTasksPerSecond: "+fmt.Sprintf("%#v", this.MaxTasksPerSecond)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TaskQueueStatus) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&taskqueue.TaskQueueStatus{")
	s = append(s, "BacklogCountHint: "+fmt.Sprintf("%#v", this.BacklogCountHint)+",\n")
	s = append(s, "ReadLevel: "+fmt.Sprintf("%#v", this.ReadLevel)+",\n")
	s = append(s, "AckLevel: "+fmt.Sprintf("%#v", this.AckLevel)+",\n")
	s = append(s, "RatePerSecond: "+fmt.Sprintf("%#v", this.RatePerSecond)+",\n")
	if this.TaskIdBlock != nil {
		s = append(s, "TaskIdBlock: "+fmt.Sprintf("%#v", this.TaskIdBlock)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TaskIdBlock) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&taskqueue.TaskIdBlock{")
	s = append(s, "StartId: "+fmt.Sprintf("%#v", this.StartId)+",\n")
	s = append(s, "EndId: "+fmt.Sprintf("%#v", this.EndId)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TaskQueuePartitionMetadata) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&taskqueue.TaskQueuePartitionMetadata{")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "OwnerHostName: "+fmt.Sprintf("%#v", this.OwnerHostName)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PollerInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&taskqueue.PollerInfo{")
	s = append(s, "LastAccessTime: "+fmt.Sprintf("%#v", this.LastAccessTime)+",\n")
	s = append(s, "Identity: "+fmt.Sprintf("%#v", this.Identity)+",\n")
	s = append(s, "RatePerSecond: "+fmt.Sprintf("%#v", this.RatePerSecond)+",\n")
	if this.WorkerVersionCapabilities != nil {
		s = append(s, "WorkerVersionCapabilities: "+fmt.Sprintf("%#v", this.WorkerVersionCapabilities)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StickyExecutionAttributes) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&taskqueue.StickyExecutionAttributes{")
	if this.WorkerTaskQueue != nil {
		s = append(s, "WorkerTaskQueue: "+fmt.Sprintf("%#v", this.WorkerTaskQueue)+",\n")
	}
	s = append(s, "ScheduleToStartTimeout: "+fmt.Sprintf("%#v", this.ScheduleToStartTimeout)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CompatibleVersionSet) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&taskqueue.CompatibleVersionSet{")
	s = append(s, "BuildIds: "+fmt.Sprintf("%#v", this.BuildIds)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TaskQueueReachability) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&taskqueue.TaskQueueReachability{")
	s = append(s, "TaskQueue: "+fmt.Sprintf("%#v", this.TaskQueue)+",\n")
	s = append(s, "Reachability: "+fmt.Sprintf("%#v", this.Reachability)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *BuildIdReachability) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&taskqueue.BuildIdReachability{")
	s = append(s, "BuildId: "+fmt.Sprintf("%#v", this.BuildId)+",\n")
	if this.TaskQueueReachability != nil {
		s = append(s, "TaskQueueReachability: "+fmt.Sprintf("%#v", this.TaskQueueReachability)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMessage(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TaskQueue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskQueue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskQueue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Kind != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TaskQueueMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskQueueMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskQueueMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxTasksPerSecond != nil {
		{
			size, err := m.MaxTasksPerSecond.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TaskQueueStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskQueueStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskQueueStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TaskIdBlock != nil {
		{
			size, err := m.TaskIdBlock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RatePerSecond != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.RatePerSecond))))
		i--
		dAtA[i] = 0x21
	}
	if m.AckLevel != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.AckLevel))
		i--
		dAtA[i] = 0x18
	}
	if m.ReadLevel != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.ReadLevel))
		i--
		dAtA[i] = 0x10
	}
	if m.BacklogCountHint != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.BacklogCountHint))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TaskIdBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskIdBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskIdBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndId != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.EndId))
		i--
		dAtA[i] = 0x10
	}
	if m.StartId != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.StartId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TaskQueuePartitionMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskQueuePartitionMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskQueuePartitionMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnerHostName) > 0 {
		i -= len(m.OwnerHostName)
		copy(dAtA[i:], m.OwnerHostName)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.OwnerHostName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PollerInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PollerInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PollerInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WorkerVersionCapabilities != nil {
		{
			size, err := m.WorkerVersionCapabilities.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.RatePerSecond != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.RatePerSecond))))
		i--
		dAtA[i] = 0x19
	}
	if len(m.Identity) > 0 {
		i -= len(m.Identity)
		copy(dAtA[i:], m.Identity)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Identity)))
		i--
		dAtA[i] = 0x12
	}
	if m.LastAccessTime != nil {
		n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.LastAccessTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.LastAccessTime):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintMessage(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StickyExecutionAttributes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StickyExecutionAttributes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StickyExecutionAttributes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ScheduleToStartTimeout != nil {
		n5, err5 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.ScheduleToStartTimeout, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.ScheduleToStartTimeout):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintMessage(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0x12
	}
	if m.WorkerTaskQueue != nil {
		{
			size, err := m.WorkerTaskQueue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CompatibleVersionSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompatibleVersionSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CompatibleVersionSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BuildIds) > 0 {
		for iNdEx := len(m.BuildIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BuildIds[iNdEx])
			copy(dAtA[i:], m.BuildIds[iNdEx])
			i = encodeVarintMessage(dAtA, i, uint64(len(m.BuildIds[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *TaskQueueReachability) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskQueueReachability) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskQueueReachability) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reachability) > 0 {
		dAtA8 := make([]byte, len(m.Reachability)*10)
		var j7 int
		for _, num := range m.Reachability {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintMessage(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TaskQueue) > 0 {
		i -= len(m.TaskQueue)
		copy(dAtA[i:], m.TaskQueue)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.TaskQueue)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BuildIdReachability) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BuildIdReachability) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BuildIdReachability) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TaskQueueReachability) > 0 {
		for iNdEx := len(m.TaskQueueReachability) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TaskQueueReachability[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMessage(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.BuildId) > 0 {
		i -= len(m.BuildId)
		copy(dAtA[i:], m.BuildId)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.BuildId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TaskQueue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovMessage(uint64(m.Kind))
	}
	return n
}

func (m *TaskQueueMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxTasksPerSecond != nil {
		l = m.MaxTasksPerSecond.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *TaskQueueStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BacklogCountHint != 0 {
		n += 1 + sovMessage(uint64(m.BacklogCountHint))
	}
	if m.ReadLevel != 0 {
		n += 1 + sovMessage(uint64(m.ReadLevel))
	}
	if m.AckLevel != 0 {
		n += 1 + sovMessage(uint64(m.AckLevel))
	}
	if m.RatePerSecond != 0 {
		n += 9
	}
	if m.TaskIdBlock != nil {
		l = m.TaskIdBlock.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *TaskIdBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartId != 0 {
		n += 1 + sovMessage(uint64(m.StartId))
	}
	if m.EndId != 0 {
		n += 1 + sovMessage(uint64(m.EndId))
	}
	return n
}

func (m *TaskQueuePartitionMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.OwnerHostName)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *PollerInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastAccessTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.LastAccessTime)
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.Identity)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.RatePerSecond != 0 {
		n += 9
	}
	if m.WorkerVersionCapabilities != nil {
		l = m.WorkerVersionCapabilities.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *StickyExecutionAttributes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WorkerTaskQueue != nil {
		l = m.WorkerTaskQueue.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.ScheduleToStartTimeout != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.ScheduleToStartTimeout)
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *CompatibleVersionSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BuildIds) > 0 {
		for _, s := range m.BuildIds {
			l = len(s)
			n += 1 + l + sovMessage(uint64(l))
		}
	}
	return n
}

func (m *TaskQueueReachability) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskQueue)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if len(m.Reachability) > 0 {
		l = 0
		for _, e := range m.Reachability {
			l += sovMessage(uint64(e))
		}
		n += 1 + sovMessage(uint64(l)) + l
	}
	return n
}

func (m *BuildIdReachability) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BuildId)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if len(m.TaskQueueReachability) > 0 {
		for _, e := range m.TaskQueueReachability {
			l = e.Size()
			n += 1 + l + sovMessage(uint64(l))
		}
	}
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TaskQueue) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskQueue{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Kind:` + fmt.Sprintf("%v", this.Kind) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TaskQueueMetadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskQueueMetadata{`,
		`MaxTasksPerSecond:` + strings.Replace(fmt.Sprintf("%v", this.MaxTasksPerSecond), "DoubleValue", "types.DoubleValue", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TaskQueueStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskQueueStatus{`,
		`BacklogCountHint:` + fmt.Sprintf("%v", this.BacklogCountHint) + `,`,
		`ReadLevel:` + fmt.Sprintf("%v", this.ReadLevel) + `,`,
		`AckLevel:` + fmt.Sprintf("%v", this.AckLevel) + `,`,
		`RatePerSecond:` + fmt.Sprintf("%v", this.RatePerSecond) + `,`,
		`TaskIdBlock:` + strings.Replace(this.TaskIdBlock.String(), "TaskIdBlock", "TaskIdBlock", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TaskIdBlock) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskIdBlock{`,
		`StartId:` + fmt.Sprintf("%v", this.StartId) + `,`,
		`EndId:` + fmt.Sprintf("%v", this.EndId) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TaskQueuePartitionMetadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskQueuePartitionMetadata{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`OwnerHostName:` + fmt.Sprintf("%v", this.OwnerHostName) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PollerInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PollerInfo{`,
		`LastAccessTime:` + strings.Replace(fmt.Sprintf("%v", this.LastAccessTime), "Timestamp", "types.Timestamp", 1) + `,`,
		`Identity:` + fmt.Sprintf("%v", this.Identity) + `,`,
		`RatePerSecond:` + fmt.Sprintf("%v", this.RatePerSecond) + `,`,
		`WorkerVersionCapabilities:` + strings.Replace(fmt.Sprintf("%v", this.WorkerVersionCapabilities), "WorkerVersionCapabilities", "v11.WorkerVersionCapabilities", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StickyExecutionAttributes) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StickyExecutionAttributes{`,
		`WorkerTaskQueue:` + strings.Replace(this.WorkerTaskQueue.String(), "TaskQueue", "TaskQueue", 1) + `,`,
		`ScheduleToStartTimeout:` + strings.Replace(fmt.Sprintf("%v", this.ScheduleToStartTimeout), "Duration", "types.Duration", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CompatibleVersionSet) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CompatibleVersionSet{`,
		`BuildIds:` + fmt.Sprintf("%v", this.BuildIds) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TaskQueueReachability) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskQueueReachability{`,
		`TaskQueue:` + fmt.Sprintf("%v", this.TaskQueue) + `,`,
		`Reachability:` + fmt.Sprintf("%v", this.Reachability) + `,`,
		`}`,
	}, "")
	return s
}
func (this *BuildIdReachability) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForTaskQueueReachability := "[]*TaskQueueReachability{"
	for _, f := range this.TaskQueueReachability {
		repeatedStringForTaskQueueReachability += strings.Replace(f.String(), "TaskQueueReachability", "TaskQueueReachability", 1) + ","
	}
	repeatedStringForTaskQueueReachability += "}"
	s := strings.Join([]string{`&BuildIdReachability{`,
		`BuildId:` + fmt.Sprintf("%v", this.BuildId) + `,`,
		`TaskQueueReachability:` + repeatedStringForTaskQueueReachability + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMessage(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TaskQueue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskQueue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskQueue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= v1.TaskQueueKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskQueueMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskQueueMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskQueueMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTasksPerSecond", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MaxTasksPerSecond == nil {
				m.MaxTasksPerSecond = &types.DoubleValue{}
			}
			if err := m.MaxTasksPerSecond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskQueueStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskQueueStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskQueueStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BacklogCountHint", wireType)
			}
			m.BacklogCountHint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BacklogCountHint |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadLevel", wireType)
			}
			m.ReadLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReadLevel |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckLevel", wireType)
			}
			m.AckLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AckLevel |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field RatePerSecond", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.RatePerSecond = float64(math.Float64frombits(v))
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIdBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaskIdBlock == nil {
				m.TaskIdBlock = &TaskIdBlock{}
			}
			if err := m.TaskIdBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskIdBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskIdBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskIdBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartId", wireType)
			}
			m.StartId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndId", wireType)
			}
			m.EndId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskQueuePartitionMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskQueuePartitionMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskQueuePartitionMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerHostName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerHostName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PollerInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PollerInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PollerInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAccessTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastAccessTime == nil {
				m.LastAccessTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.LastAccessTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Identity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field RatePerSecond", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.RatePerSecond = float64(math.Float64frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerVersionCapabilities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WorkerVersionCapabilities == nil {
				m.WorkerVersionCapabilities = &v11.WorkerVersionCapabilities{}
			}
			if err := m.WorkerVersionCapabilities.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StickyExecutionAttributes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StickyExecutionAttributes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StickyExecutionAttributes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerTaskQueue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WorkerTaskQueue == nil {
				m.WorkerTaskQueue = &TaskQueue{}
			}
			if err := m.WorkerTaskQueue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduleToStartTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ScheduleToStartTimeout == nil {
				m.ScheduleToStartTimeout = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.ScheduleToStartTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompatibleVersionSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompatibleVersionSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompatibleVersionSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuildIds = append(m.BuildIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskQueueReachability) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskQueueReachability: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskQueueReachability: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskQueue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskQueue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v v1.TaskReachability
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= v1.TaskReachability(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Reachability = append(m.Reachability, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMessage
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthMessage
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Reachability) == 0 {
					m.Reachability = make([]v1.TaskReachability, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v v1.TaskReachability
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessage
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= v1.TaskReachability(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Reachability = append(m.Reachability, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Reachability", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BuildIdReachability) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BuildIdReachability: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BuildIdReachability: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuildId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskQueueReachability", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskQueueReachability = append(m.TaskQueueReachability, &TaskQueueReachability{})
			if err := m.TaskQueueReachability[len(m.TaskQueueReachability)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
